ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="Administracion"),
    path('cursos/', include('cursos.urls')),
    path('carro/', include('carro.urls')),
    path('asignaciones/', include('asignaciones.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('', include('stock.urls')),
    path('reconocimiento/', include('reconocimiento.urls')),

#     path('jet_api/', include('jet_django.urls')),
#     path('admin/', admin.site.urls),
]

carro/urls.py
from django.urls import path

from . import views

app_name="carro"

urlpatterns=[
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

stock/urls.py
from xml.dom.minidom import Document
from django.urls import path
from stock import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="Home"),
    path('carrito', views.carrito, name="Carrito"),
    path('contacto', views.contacto, name="Contacto"),
    path('checkout', views.checkout, name="Checkout"),
    path('manual_usuario', views.manual_usuario, name="manual_usuario"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/models.py
from django.db import models

stock/views.py
from django.http import HttpResponse
from django.template import Template, Context
from django.template import loader
from django.shortcuts import render
from carro.carro import Carro
from cursos.models import articulos
from usuarios.models import usuarios
from carro.carro import Carro


# Create your views here.

def home(request):

    carro = Carro(request)

    arts = articulos.objects.all()

    ultimos_articulos=[]
    #print("################################################")
    if len(arts)>3:
        for i in range(len(arts)-4, len(arts)):
            ultimos_articulos.append(arts[i])
    else:
        for i in range(0, len(arts)):
            ultimos_articulos.append(arts[i])
        #print(ultimos_articulos)
    #print("################################################")
    return render(request, "stock/home.html", {"arts":arts, "articulos":ultimos_articulos})
    #return render(request, "stock/home.html")

def carrito(request):

    return render(request, "stock/carrito.html")

def contacto(request):

    return render(request, "stock/contacto.html")

def manual_usuario(request):

    return render(request, "stock/manual_usuario.html")

def checkout(request):
    info_usuario = usuarios.objects.all()
    pedido_valido = True
    return render(request, "stock/checkout.html", {"info_usuario":info_usuario, "pedido_valido": pedido_valido})
    # return render(request, "stock/checkout.html", {"info_usuario":info_usuario})

stock/templates/stock/base.html
{%load static%}
{% load admin_urls %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'stock/img/fav2.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	{% if request.path == '/'%}
	<title>Music Academy</title>
	{% elif request.path == '/cursos/'%}
	<title>Music Academy - Catalogo</title>
	{% elif request.path == '/carrito'%}
	<title>Music Academy - Asignación</title>
	{% elif request.path == '/contacto'%}
	<title>Music Academy - Contacto</title>
	{% elif request.path == '/checkout'%}
	<title>Music Academy - Checkout</title>
	{% elif request.path == '/autenticacion/'%}
	<title>Music Academy - Registro</title>
	{% elif request.path == '/autenticacion/iniciar_sesion'%}
	<title>Music Academy - Iniciar sesión</title>
	{% elif request.path == '/autenticacion/perfil'%}
	<title>Music Academy - Perfil</title>
	{% elif request.path == '/autenticacion/reset_password/'%}
	<title>Music Academy - Recuperar cuenta</title>
	{% elif request.path == '/autenticacion/reset_password_sent/'%}
	<title>Music Academy - Recuperar cuenta</title>
	{% elif request.path == '/autenticacion/reset/Mw/set-password/'%}
	<title>Music Academy - Recuperar cuenta</title>
	{% elif request.path == '/autenticacion/reset_password_complete/'%}
	<title>Music Academy - Recuperar cuenta</title>
	{% else %}
	<title>Music Academy - Producto</title>
	{% endif %}
	<!--
		CSS
		============================================= -->
	<link rel="stylesheet" href="{% static 'stock/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/ion.rangeSlider.css' %}" />
	<link rel="stylesheet" href="{% static 'stock/css/ion.rangeSlider.skinFlat.css' %}" />
	<link rel="stylesheet" href="{% static 'stock/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/main.css' %}">
</head>

<body class="Bodyss">
	<style>
	.nav-item:hover {
		/* Estilo al pasar el ratón sobre el texto */
		color: red; /* Cambia a color rojo cuando se pasa el ratón */
	  }
	</style>
	<!-- Start Header Area -->
	<header class="header_area sticky-header"style="background-color:#1BC0E5;">
		<div class="main_menu" >
			<nav class="navbar navbar-expand-lg navbar-light main_box" style="background-color:#86dade;">
				<div class="container" style="background-color:#ffffff;">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="{% url 'Home' %}"><img src="{% static 'stock/img/logo2.png'%}" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #31fa08;">
						<span class="icon-bar" style="background-color:#45e60f;"></span>
						<span class="icon-bar" style="background-color:#64f006;"></span>
						<span class="icon-bar" style="background-color:#31fa08;"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent" style="background-color:#5bd8e6; width: 1900px; height: 50px;">
						<ul class="nav navbar-nav menu_nav ml-auto" style="background-color: #5bd8e6; ">
							<li class="nav-item {% if request.path == '/' %}active{% endif %}"><a class="nav-link" href="{% url 'Home' %} "style="color: #04013f">Inicio</a></li>
							<li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false" style="color: #04013f">Cursos</a>
								<ul class="dropdown-menu">
									<li class="nav-item {% if request.path == '/cursos/' %}active{% endif %}"><a class="nav-link" href="{% url 'Catalogo' %}"style="color: #04013f">Catálogo</a></li>
									<!--<li class="nav-item"><a class="nav-link" href="ProductDetailsPages/ProductDetails1.html">Detalles de Producto</a></li>-->
									<!--<li class="nav-item"><a class="nav-link" href="checkout.html">Confirmar Producto</a></li>-->
									<li class="nav-item {% if request.path == '/carrito' %}active{% endif %}"><a class="nav-link" href="{% url 'Carrito'%}"style="color: #04013f">Asignación</a></li>
									<!--<li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmacion</a></li>-->
								</ul>
							</li>
							<li class="nav-item {% if request.path == '/contacto' %}active{% endif %}"><a class="nav-link" href="{% url 'Contacto'%}"style="color: #04013f">Contacto</a></li>

							{% if user.is_authenticated %}
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
									aria-expanded="false">{{user.username}}</a>
									<ul class="dropdown-menu">
										{% if user.is_staff is not True%}
											<li class="nav-item {% if request.path == '/autenticacion/perfil' %}active{% endif %}"><a class="nav-link" href="{% url 'perfil'%}"style="color: #04013f">Mi perfil</a></li>
										{% else %}
										<li class="nav-item {% if request.path == '/autenticacion/perfil' %}active{% endif %}"><a class="nav-link" href="{% url 'admin:index' %}"style="color: #04013f">Administracion</a></li>
										{% endif %}
											<li class="nav-item"><a class="nav-link" href="{% url 'cerrar_sesion'%}"style="color: #04013f">Cerrar sesión</a></li>
									</ul>
								</li>
							{% else %}
								<li class="nav-item submenu dropdown"style="color: #04013f">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
									aria-expanded="false"style="color: #04013f">Iniciar sesión</a>
									<ul class="dropdown-menu">
										<li class="nav-item {% if request.path == '/autenticacion/' %}active{% endif %}"><a class="nav-link" href="{% url 'Autenticacion' %}"style="color: #04013f; ">Registrarse</a></li>
										<li class="nav-item {% if request.path == '/autenticacion/iniciar_sesion' %}active{% endif %}"><a class="nav-link" href="{% url 'iniciar_sesion' %}"style="color: #04013f; ">Iniciar sesión</a></li>
										<li class="nav-item {% if request.path == '/autenticacion/reset_password/' %}active{% endif %}"><a class="nav-link" href="{% url 'reset_password'%}"style="color: #04013f; ">Recuperar cuenta</a></li>
									</ul>
								</li>
							{% endif %}


						</ul>


						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item"><a class="cart"><span class="ti-user" style="color: rgb(2, 2, 2);"> </span></a> </li>
						</ul>
						
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Search Here">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>
	</header>
	<!-- End Header Area -->

	<!-- Start changed Area -->
	{%block content %}

	{% endblock %}
	<!-- End changed Area -->



	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Sobre Nosotros</h6>
						<p>
							Music academy te asegura un aprendizaje seguro y consante para que te desarrolles en el arte y en la musica.
						</p>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Redes Sociales</h6>
						<p>Siguenos en nuestras redes sociales y enterate de promociones en nuestros cursos.</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
				<p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Todos los Derechos Reservados</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->

	<script src="{% static 'stock/js/vendor/jquery-2.2.4.min.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'stock/js/vendor/bootstrap.min.js'%}"></script>
	<script src="{% static 'stock/js/jquery.ajaxchimp.min.js'%}"></script>
	<script src="{% static 'stock/js/jquery.nice-select.min.js'%}"></script>
	<script src="{% static 'stock/js/jquery.sticky.js'%}"></script>
	<script src="{% static 'stock/js/nouislider.min.js'%}"></script>
	<script src="{% static 'stock/js/countdown.js'%}"></script>
	<script src="{% static 'stock/js/jquery.magnific-popup.min.js'%}"></script>
	<script src="{% static 'stock/js/owl.carousel.min.js'%}"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="{% static 'stock/js/gmaps.min.js'%}"></script>
	<script src="{% static 'stock/js/main.js'%}"></script>
</body>

</html>

stock/templates/stock/carrito.html
{% extends "stock/base.html"%}

{% load static %}
{% block content %}

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1 style="color: black;">Asignación</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'Home' %}"style="color: black;">Inicio<span class="lnr lnr-arrow-right"></span></a>
						<!--<a href="#">Shop<span class="lnr lnr-arrow-right"></span></a>-->
						<a href="{% url 'Carrito' %}"style="color: black;">Asignacion</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

    {% if request.user.is_authenticated %}

        <!--================Cart Area =================-->
        <section class="cart_area">
            <div class="container">
                <div class="cart_inner">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Curso</th>
                                    <th scope="col">Precio </th>
                                  <!--   <th scope="col">Cantidad</th>-->
                                </tr>
                            </thead>
                            <tbody>                                

                                {% if request.session.carro.items %}
                                    {% for key, value in request.session.carro.items %}

                                    <!--================Inicio Producto Individual =================-->
                                    <tr>
                                        <td>
                                            <div class="media">
                                                <div class="d-flex">
                                                    <img src="{{value.imagen}}" alt="" style="width: 50px; ">
                                                </div>
                                                <div class="media-body">
                                                    <p>{{value.nombre}}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <h5>Q{{value.precio }}</h5>
                                        </td>

                                        <td>
                                            <form action="{%url 'carro:restar' value.producto_id%}">
                                                <input type="submit" action="{%url 'carro:restar' value.producto_id%}" value="Eliminar" class="gray_btn">
                                            </form>
                                        </td>
                                    </tr>
                                    <!--================Fin Producto Individual =================-->
                                    <!--================INICIO MODAL =================-->
                                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confimarción de eliminación</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                </div>
                                                <div class="modal-body">
                                                ¿Ésta seguro de eliminar este producto de su asignación?
                                                </div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Regresar</button>
                                                <form action="{%url 'carro:restar' value.producto_id%}">
                                                    <button type="submit" type="button" class="btn btn-primary">Confirmar</button>
                                                </form>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    <!--================FIN MODAL =================-->

                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="4">
                                            <div class="alert alert-danger text-center">
                                                Sin cursos en la asignacion
                                            </div>
                                        </td>
                                    </tr>
                                {% endif %}


                                <tr>

                                    <td>
                                        <h5>Total</h5>
                                    </td>
                                    <td>
                                        <h5>Q{{importe_total_carro}}</h5>
                                    </td>
                                </tr>
                                <tr class="shipping_area">
                           
                                 
                                </tr>
                                <tr class="out_button_area">
                                    <td>

                             

                                    </td>
                                    <td>
                                        <div class="checkout_btn_inner d-flex align-items-center" style="float: right;">
                                            <a class="gray_btn" href="{% url 'Catalogo' %}">Volver a catálogo</a>
                                            {% if request.session.carro.items %}
                                                <a class="primary-btn" href="{% url 'Checkout' %}">Pagar</a>
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Cart Area =================-->
    
    {% else %}
        <br></br>
        <div class="alert alert-danger text-center">Debe iniciar sesión</div>
        <br></br>
    {% endif %}


{% endblock %}

stock/templates/stock/contacto.html
{% extends "stock/base.html"%}

{% load static %}
{% block content %}
    <!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1 style= "color:rgb(0, 0, 0);">Contacto</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'Home' %}" style= "color:rgb(0, 0, 0);">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="{% url 'Contacto' %}" style= "color:rgb(0, 0, 0);">Contacto</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->
	<hr>

	<!--================Contact Area =================-->
	<section class="contact_area section_gap_bottom">
		<div class="container" style="background-color:#cdf3ee;">
			<div class="row justify-content-center">
					<div class="contact_info">
						<div class="info_item">
							<i class="lnr lnr-home" style= "color:rgb(68, 0, 255);"></i>
							<h6>Flores, Petén</h6>
							<p>Zona 3 casa 56 Flores</p>
						</div>
						<div class="info_item">
							<i class="lnr lnr-phone-handset" style= "color:rgb(68, 0, 255);"></i>
							<h6><a href="#">87549865</a></h6>
							<p>Unicamente fines de semana</p>
						</div>
						<div class="info_item">
							<i class="lnr lnr-envelope" style= "color:rgb(68, 0, 255);"></i>
							<h6><a href="#">musicacademy997@gmail.com</a></h6>
							<p>Disponible las 24h</p>
						</div>
					</div>
			</div>
		</div>
	</section>
	<!--================Contact Area =================-->
	<hr>

{% endblock %}

stock/templates/stock/home.html
{% extends "stock/base.html"%}

{% load static %}

{% block content %}
	<!-- start banner Area -->
	<section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
					<div class="active-banner-slider owl-carousel">
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
									<h1 id="Banner1">Curso <br>Guitarra</h1>
									<p  style="color: #000000">Aprende a tocar guitarra clasica, y adentrate en la dulzura de sus cuerdas</p>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img1" style="width:400px; height:100px; margin-bottom: 300px; margin-left: 200px;">
									<img class="img-fluid" src="{% static 'stock/img/banner/banner-img.png'%}" alt="" >
								</div>
							</div>
						</div>
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
									<h1 id="Banner2">Curso  <br>Marimba</h1>
									<p  style="color: #000000">Aprende el insrumento musical mas especial, y conoce sus secretos guardados por nuestros antepasados.</p>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img2" style="width:400px; height:100px; margin-bottom: 300px; margin-left: 200px;">
									<img class="img-fluid" src="{% static 'stock/img/banner/banner-img2.png'%}" alt="">
								</div>
							</div>
						</div>		
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
									<h1 id="Banner3">Curso <br>Piano</h1>
									<p style="color: #000000" >Adentrate en el instrumento mas versatil, y acompaña cualquier pieza musical.</p>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img3" style="width:400px; height:100px; margin-bottom: 300px; margin-left: 200px;">
									<img class="img-fluid" src="{% static 'stock/img/banner/banner-img3.png'%}" alt="">
								</div>
							</div>
						</div>	
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->


	<!-- Start category Area -->
	<section class="category-area">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-6 text-center">
					<div class="section-title">
						<h1>Music Academy Siempre Contigo</h1>
					</div>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-lg-8 col-md-12">
					<div class="row">
						<div class="col-lg-8 col-md-8">
							<div class="single-deal">
								<div class="overlay"></div>
								<img class="img-fluid w-100" src="{% static 'stock/img/category/c1.jpg'%}" alt="">
								<a href="{% static 'stock/img/category/c1.jpg'%}" class="img-pop-up" target="_blank">
									<div class="deal-details">
										<h6 class="deal-title">Al aprender musica</h6>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-4 col-md-4">
							<div class="single-deal">
								<div class="overlay"></div>
								<img class="img-fluid w-100" src="{% static 'stock/img/category/c2.jpg'%}" alt="">
								<a href="{% static 'stock/img/category/c2.jpg'%}" class="img-pop-up" target="_blank">
									<div class="deal-details">
										<h6 class="deal-title">A compartir la musica</h6>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-4 col-md-4">
							<div class="single-deal">
								<div class="overlay"></div>
								<img class="img-fluid w-100" src="{% static 'stock/img/category/c3.jpg'%}" alt="">
								<a href="{% static 'stock/img/category/c3.jpg'%}" class="img-pop-up" target="_blank">
									<div class="deal-details">
										<h6 class="deal-title">A entender la musica</h6>
									</div>
								</a>
							</div>
						</div>
						<div class="col-lg-8 col-md-8">
							<div class="single-deal">
								<div class="overlay"></div>
								<img class="img-fluid w-100" src="{% static 'stock/img/category/c4.jpg'%}" alt="">
								<a href="{% static 'stock/img/category/c4.jpg'%}" class="img-pop-up" target="_blank">
									<div class="deal-details">
										<h6 class="deal-title">A enseñar la musica</h6>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End category Area -->


	<!-- single product slide -->
	<section class="lattest-product-area pb-40 category-list">
		<!--Inicio de fila 4 items-->
		<div class="single-product">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 text-center">
						<div class="section-title">
							<h1>Nuestros Cursos</h1>
							<p>Conoce nuestros cursos ya disponibles para ti.</p>
						</div>
					</div>
				</div>
				<div class="row">
					{%for arts in articulos %}
					{% if arts.disponibilidad%}
					<!-- Producto -->
					<div class="col-lg-3 col-md-6">
						<div class="single-product">
							<img class="img-fluid" src="{{arts.imagen.url}}" alt="imagen {{arts.imagen.url}}" title="{{arts.nombre}}">
							<div class="product-details">
								<h6>{{arts.nombre}}</h6>
								<div class="price">
									<h6>Q{{arts.descuento |stringformat:".2f"}}</h6>
									<h6 class="l-through">Q{{arts.precio |stringformat:".2f"}}</h6>
								</div>
								{% if arts.cantidad > 0%}
									<p>En existencia: {{arts.cantidad}}</p>
								{% else %}
									<p>Sin existencias</p>
								{% endif %}
								<div class="prd-bottom">
									{% if arts.cantidad > 0%}
									{% if user.is_authenticated and user.is_staff is not True%}
										<a href="{%url 'carro:agregar' arts.id%}" class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">Asignar</p>
										</a>
									{% else %}
										<a class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">Admin</p>
										</a>
									{% endif %}
									{% else %}
									<a class="social-info">
										<span class="ti-bag"></span>
										<p class="hover-text">Cupo lleno</p>
									</a>
									{% endif %}
									<a href="{% url 'Producto' id=arts.id %}" class="social-info">
										<span class="lnr lnr-move"></span>
										<p class="hover-text">Detalles</p>
									</a>
								</div>
							</div>
						</div>
					</div>
					<!-- Fin Producto -->
					{%endif%}
					{% endfor %}
				</div>
			</div>
		</div>
		<!--Fin de fila 4 items-->
	</section>
	<!-- end product Area -->


{% endblock %}